# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/launcher.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(524, 608)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/res/ice9_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 524, 804))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.labelMasterState = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelMasterState.setMinimumSize(QtCore.QSize(80, 0))
        self.labelMasterState.setObjectName("labelMasterState")
        self.gridLayout_3.addWidget(self.labelMasterState, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.labelMasterPing = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelMasterPing.setText("")
        self.labelMasterPing.setObjectName("labelMasterPing")
        self.gridLayout_3.addWidget(self.labelMasterPing, 0, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(50, 50))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 180))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 491, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(15, 10, 15, 10)
        self.gridLayout.setObjectName("gridLayout")
        self.labelNetSpdUnitreeDown = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdUnitreeDown.setFont(font)
        self.labelNetSpdUnitreeDown.setText("")
        self.labelNetSpdUnitreeDown.setObjectName("labelNetSpdUnitreeDown")
        self.gridLayout.addWidget(self.labelNetSpdUnitreeDown, 5, 3, 1, 1)
        self.pushButtonNetSpdUnitree = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonNetSpdUnitree.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonNetSpdUnitree.setFont(font)
        self.pushButtonNetSpdUnitree.setObjectName("pushButtonNetSpdUnitree")
        self.gridLayout.addWidget(self.pushButtonNetSpdUnitree, 4, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.labelNetSpdBaseDown = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdBaseDown.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdBaseDown.setFont(font)
        self.labelNetSpdBaseDown.setText("")
        self.labelNetSpdBaseDown.setObjectName("labelNetSpdBaseDown")
        self.gridLayout.addWidget(self.labelNetSpdBaseDown, 1, 3, 1, 1)
        self.labelNetSpdUnitreeLatency = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdUnitreeLatency.setFont(font)
        self.labelNetSpdUnitreeLatency.setText("")
        self.labelNetSpdUnitreeLatency.setObjectName("labelNetSpdUnitreeLatency")
        self.gridLayout.addWidget(self.labelNetSpdUnitreeLatency, 4, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 3, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 0, 4, 1, 1)
        self.labelNetSpdBaseLatency = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdBaseLatency.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdBaseLatency.setFont(font)
        self.labelNetSpdBaseLatency.setText("")
        self.labelNetSpdBaseLatency.setObjectName("labelNetSpdBaseLatency")
        self.gridLayout.addWidget(self.labelNetSpdBaseLatency, 0, 3, 1, 1)
        self.pushButtonNetSpdBase = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButtonNetSpdBase.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonNetSpdBase.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonNetSpdBase.setFont(font)
        self.pushButtonNetSpdBase.setObjectName("pushButtonNetSpdBase")
        self.gridLayout.addWidget(self.pushButtonNetSpdBase, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMinimumSize(QtCore.QSize(50, 0))
        self.label_11.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 5, 5, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(50, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setBaseSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 5, 1, 1)
        self.labelNetSpdUnitreeTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdUnitreeTime.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdUnitreeTime.setFont(font)
        self.labelNetSpdUnitreeTime.setText("")
        self.labelNetSpdUnitreeTime.setObjectName("labelNetSpdUnitreeTime")
        self.gridLayout.addWidget(self.labelNetSpdUnitreeTime, 4, 5, 1, 2)
        self.labelNetSpdBaseUp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdBaseUp.setMinimumSize(QtCore.QSize(85, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdBaseUp.setFont(font)
        self.labelNetSpdBaseUp.setObjectName("labelNetSpdBaseUp")
        self.gridLayout.addWidget(self.labelNetSpdBaseUp, 1, 6, 1, 1)
        self.labelNetSpdUnitreeUp = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdUnitreeUp.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdUnitreeUp.setFont(font)
        self.labelNetSpdUnitreeUp.setText("")
        self.labelNetSpdUnitreeUp.setObjectName("labelNetSpdUnitreeUp")
        self.gridLayout.addWidget(self.labelNetSpdUnitreeUp, 5, 6, 1, 1)
        self.labelNetSpdBaseTime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelNetSpdBaseTime.setMinimumSize(QtCore.QSize(161, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.labelNetSpdBaseTime.setFont(font)
        self.labelNetSpdBaseTime.setText("")
        self.labelNetSpdBaseTime.setObjectName("labelNetSpdBaseTime")
        self.gridLayout.addWidget(self.labelNetSpdBaseTime, 0, 5, 1, 2)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem8 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem8)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 320))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 491, 291))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(15, 10, 15, 10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonMapvizSave = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonMapvizSave.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMapvizSave.setFont(font)
        self.pushButtonMapvizSave.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.pushButtonMapvizSave.setObjectName("pushButtonMapvizSave")
        self.gridLayout_2.addWidget(self.pushButtonMapvizSave, 10, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonMapvizLaunch = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonMapvizLaunch.setMinimumSize(QtCore.QSize(95, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMapvizLaunch.setFont(font)
        self.pushButtonMapvizLaunch.setObjectName("pushButtonMapvizLaunch")
        self.horizontalLayout_2.addWidget(self.pushButtonMapvizLaunch)
        self.pushButtonMapvizSafeQuit = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButtonMapvizSafeQuit.setMinimumSize(QtCore.QSize(95, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMapvizSafeQuit.setFont(font)
        self.pushButtonMapvizSafeQuit.setObjectName("pushButtonMapvizSafeQuit")
        self.horizontalLayout_2.addWidget(self.pushButtonMapvizSafeQuit)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.frame = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.frame.setMinimumSize(QtCore.QSize(160, 35))
        self.frame.setStyleSheet("background-color: rgb(233, 185, 110);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(10, 5, 47, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(239, 41, 41);")
        self.label_12.setObjectName("label_12")
        self.pushButtonMapvizForceQuit = QtWidgets.QPushButton(self.frame)
        self.pushButtonMapvizForceQuit.setGeometry(QtCore.QRect(65, 5, 90, 24))
        self.pushButtonMapvizForceQuit.setMinimumSize(QtCore.QSize(90, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonMapvizForceQuit.setFont(font)
        self.pushButtonMapvizForceQuit.setStyleSheet("color: rgb(239, 41, 41);")
        self.pushButtonMapvizForceQuit.setObjectName("pushButtonMapvizForceQuit")
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.checkBoxShowObstacle = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowObstacle.setFont(font)
        self.checkBoxShowObstacle.setObjectName("checkBoxShowObstacle")
        self.gridLayout_2.addWidget(self.checkBoxShowObstacle, 8, 1, 1, 1)
        self.checkBoxShowUnitreeImg = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowUnitreeImg.setFont(font)
        self.checkBoxShowUnitreeImg.setObjectName("checkBoxShowUnitreeImg")
        self.gridLayout_2.addWidget(self.checkBoxShowUnitreeImg, 6, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.lineEditBingAPI = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lineEditBingAPI.setFont(font)
        self.lineEditBingAPI.setObjectName("lineEditBingAPI")
        self.horizontalLayout_3.addWidget(self.lineEditBingAPI)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 5, 0, 1, 2)
        self.checkBoxShowSlamMap = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowSlamMap.setFont(font)
        self.checkBoxShowSlamMap.setObjectName("checkBoxShowSlamMap")
        self.gridLayout_2.addWidget(self.checkBoxShowSlamMap, 7, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 11, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 9, 1, 1, 1)
        self.checkBoxShowCam = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowCam.setFont(font)
        self.checkBoxShowCam.setObjectName("checkBoxShowCam")
        self.gridLayout_2.addWidget(self.checkBoxShowCam, 8, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.checkBoxShowTraj = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowTraj.setFont(font)
        self.checkBoxShowTraj.setObjectName("checkBoxShowTraj")
        self.gridLayout_2.addWidget(self.checkBoxShowTraj, 7, 1, 1, 1)
        self.checkBoxShowSatMap = QtWidgets.QCheckBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxShowSatMap.setFont(font)
        self.checkBoxShowSatMap.setObjectName("checkBoxShowSatMap")
        self.gridLayout_2.addWidget(self.checkBoxShowSatMap, 6, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem13)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.statusbar.setFont(font)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UGI Launcher"))
        self.labelMasterState.setText(_translate("MainWindow", "Unknown"))
        self.label.setText(_translate("MainWindow", "ROS master:"))
        self.label_13.setText(_translate("MainWindow", "Latency:"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/res/ice9_logo.png\" height=\"50\" width=\"50\"/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Network speed test"))
        self.pushButtonNetSpdUnitree.setText(_translate("MainWindow", "Unitree Go1"))
        self.label_6.setText(_translate("MainWindow", "Latency:"))
        self.label_5.setText(_translate("MainWindow", "Latency:"))
        self.pushButtonNetSpdBase.setText(_translate("MainWindow", "Basestation"))
        self.label_7.setText(_translate("MainWindow", "Download:"))
        self.label_4.setText(_translate("MainWindow", "Download:"))
        self.label_11.setText(_translate("MainWindow", "Upload:"))
        self.label_8.setText(_translate("MainWindow", "Upload:"))
        self.labelNetSpdBaseUp.setText(_translate("MainWindow", "1"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Mapviz"))
        self.pushButtonMapvizSave.setText(_translate("MainWindow", "Save as Defaults"))
        self.pushButtonMapvizLaunch.setText(_translate("MainWindow", "Launch"))
        self.pushButtonMapvizSafeQuit.setText(_translate("MainWindow", "Safe Quit"))
        self.label_12.setText(_translate("MainWindow", "Danger!"))
        self.pushButtonMapvizForceQuit.setText(_translate("MainWindow", "Force Quit"))
        self.checkBoxShowObstacle.setText(_translate("MainWindow", "Show Obstacles"))
        self.checkBoxShowUnitreeImg.setText(_translate("MainWindow", "Show Unitree GO 1 Image"))
        self.label_9.setText(_translate("MainWindow", "Bing Map API:"))
        self.checkBoxShowSlamMap.setText(_translate("MainWindow", "Show SLAM Map"))
        self.checkBoxShowCam.setText(_translate("MainWindow", "Show Camera View"))
        self.label_10.setText(_translate("MainWindow", "Configurations"))
        self.checkBoxShowTraj.setText(_translate("MainWindow", "Show Trajectory"))
        self.checkBoxShowSatMap.setText(_translate("MainWindow", "Show Satellite Map"))

import resources_rc
